# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-30 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alertas', '0011_auto_20160830_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='detection',
            name='location_lat',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detection',
            name='location_long',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='picture',
            name='image',
            field=models.ImageField(null=True, upload_to='img'),
        ),
    ]
