# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-06 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alertas', '0012_auto_20160930_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='threat',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='threat',
            name='code',
            field=models.IntegerField(),
        ),
    ]
